final version --MADE
made-mlops-2022/iskornev_matthew_made_mlops_22 pull request #1
Opened 2022-11-04 19:22 UTC by IskornevME

0. ### Архитектурные решения

- Структура проекта базируется на  cookiecutter-data-science.
- Данные загружаются с kaggle при помощи KaggleApi
- EDA отчет генерирует при помощи скрипта
- Для обработки данных написан кастомные трансформер с OneHotEncoder и StandardScaler
- При обучении данные делятся на train и test. Если при запуске train указать mdoel.grid_search=true,
   то запускается grid search и делается дополнительное разбиение на валидационную часть
- После обучения модель и тестовые данные сохраняются в отдельные пути (см. README)
- Для конфигов используется hydra (формат конфигов - yaml). Чтобы указать типы параметров используются   
   датаклассы. 
- Для обучения представлены 2 полноценные конфигурации: KNeighborsClassifier и RandomForestClassifier
- Для train и predict написаны отдельные функции, которые вызываются как утилиты командной строки
- Для загрузки данных и создания синтетических данных для тестов созданы специальные команды через entry
   points в setup.py
- Для логгирования используется logging
- Mlflow развернут локально. Зарегистрировано 2 модели (см. скрин ниже)
- В качестве метрик логгировал сразу несколько: f1-score, accuracy, roc_auc
- Для тестов используется unittest. Тесты проверяют преобразование данных, а также train и predict пайплайны
- Тесты и flake8 включены в CI, настроенный через GitHub Actions.

### Самооценка
1. В пулл-реквесте проведена самооценка, распишите по каждому пункту выполнен ли критерий или нет и на сколько баллов(частично или полностью) (**1 балл**) ☑️

2. Выполнено EDA, закоммитьте ноутбук в папку с ноутбуками (**1 балл**) Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы) ☑️

     Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + **1   
     балл**) ☑️

3. Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в 
     readme инструкцию по запуску (**3 балла)** ☑️

4. Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход 
     артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по  
     вызову записана в readme (**3 балла**) ☑️

5. Проект имеет модульную структуру (**2 балла**) ☑️

6. Использованы логгеры (**2 балла**) ☑️

7. Написаны тесты на отдельные модули и на прогон обучения и predict (**3 балла**) ☑️

8. Для тестов генерируются синтетические данные, приближенные к реальным (**2 балл**а) ☑️
     Используется DataSynthesizer

9. Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные 
     конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (**3 
     балла**) ☑️

10. Используются датаклассы для сущностей из конфига, а не голые dict (**2 балла**) ☑️

11. Написан и протестирован кастомный трансформер(**3 балла**) ☑️

12. В проекте зафиксированы все зависимости (**1 балл**) ☑️

13. Настроен CI для прогона тестов, линтера на основе github actions (**3 балла**). ☑️

Дополнительные баллы=)

Используйте hydra для конфигурирования (https://hydra.cc/docs/intro/) - **3 балла** ☑️

Mlflow

разверните локально mlflow или на какой-нибудь виртуалке (**1 балл**) ☑️

залогируйте метрики (**1 балл**) ☑️

воспользуйтесь Model Registry для регистрации модели(**1 балл**) Приложите скриншот с вашим mlflow run DVC ☑️

выделите в своем проекте несколько entrypoints в виде консольных утилит (**1 балл**) ☑️

добавьте датасет под контроль версий (1 балл) ❌

сделайте dvc пайплайн(связывающий запуск нескольких entrypoints) для изготовления модели(1 балл) ❌

**Итого: 36 / 38 баллов**

Скриншоты mlflow:
![image](https://user-images.githubusercontent.com/55106609/200057438-2b50188b-8019-4520-a0c2-23e9a3919df8.png)

Зарегистрированные модели:
![image](https://user-images.githubusercontent.com/55106609/200057606-515ee82b-5450-4076-8c3e-1db6d4e14399.png)
![image](https://user-images.githubusercontent.com/55106609/200057629-c476ff3d-765e-4209-b33d-ad54435081a0.png)
![image](https://user-images.githubusercontent.com/55106609/200057747-60af2055-d962-417e-adbc-f28ef2486c50.png)

2022-11-14 22:16 UTC, SVizor42 commented on ml_project/src/data/data_load.py
> +from src.data import PATH_TO_DATA
Локальные импорты идут после основных пакетов

2022-11-14 22:17 UTC, SVizor42 commented on ml_project/src/features/build_features.py
> +# NUMERIC_FEATURES = ['age', 'trestbps', 'chol', 'thalach', 'oldpeak']
Лучше убрать закомментированные участки кода

2022-11-14 22:21 UTC, SVizor42 commented on ml_project/src/models/model_fit_predict.py
> +                          'metric': ['minkowski', 'euclidean']}
Параметры лучше не хардкодить, а передавать через конфиг или хотя бы константу

2022-11-14 22:24 UTC, SVizor42 commented on ml_project/src/models/train_pipeline.py
> +    target = df['condition']
Таргет лучше не хардкодить, а передавать через конфиг или константы

2022-11-15 17:58 UTC, SVizor42 commented on ml_project/reports/make_report.py
> +from src.data import PATH_TO_DATA
Локальные импорты идут после основных пакетов

2022-11-15 18:00 UTC, SVizor42 commented on ml_project/src/models/train_pipeline.py
> +# logger.info("ssss")
Закомментированный блок лучше убрать

2022-11-15 18:01 UTC, SVizor42 commented on ml_project/src/models/train_pipeline.py
> +    df = pd.read_csv(PATH_TO_DATA.joinpath('raw/heart_cleveland_upload.csv'))
Лучше передавать пути ко всем файлам с данными и моделям через конфиг

2022-11-15 18:36 UTC, SVizor42 commented on ml_project/src/models/train_pipeline.py
> +    df_processed.to_csv(PATH_TO_DATA.joinpath('processed/heart_cleveland_upload.csv'), index=False)
Здесь обучение может "упасть", т.к. указанный путь к `processed` может не существовать

2022-11-15 18:40 UTC, SVizor42 commented on ml_project/src/models/model_fit_predict.py
> +import os
Локальные импорты идут после основных пакетов

2022-11-15 18:50 UTC, SVizor42 commented on ml_project/src/models/model_fit_predict.py
> +            trans.fit()
Зачем вновь обучать трансформер на валидационной части? Надо, например для скейлера, посчитывать статистики на тренировочной выборке и уже применять их к валидационной части

2022-11-15 18:53 UTC, SVizor42 commented on ml_project/src/models/predict_pipeline.py
> +    )
Трансформер не нужно вновь обучать. Его необходимо было сохранить в тренировочном модуле - либо отдельно, либо в виде готового пайплайна с моделью

2022-11-15 18:54 UTC, SVizor42 commented on ml_project/src/models/predict_pipeline.py
> +                   'data/predicted_target.txt')
Почему не `@hydra`?

2022-11-15 18:59 UTC, SVizor42 requested changes
Посмотри, пожалуйста, комментарии. Нужно будет поправить некоторые вещи.

На что нужно обратить особое внимание:
1. Пути, имена признаков и таргетов нужно стараться передавать через конфиги.
2. Последовательность импортов.
3. Исключить из трекинга "мусорные" папки (`__pycahe__` и т.д.).
4. Добавить метки `hw1` и `MADE`/`TECHNOPARK`.

2022-11-20 11:09 UTC, IskornevME commented
> 

Спасибо за замечания!
Постарался все поправить, посмотрите пожалуйста

2022-11-20 11:15 UTC, IskornevME commented on ml_project/src/models/predict_pipeline.py
> +                   'data/predicted_target.txt')
Показалось удобным, что можно передавать пути через флажок с помощью click. Хотя сейчас понимаю, что можно было обойтись гидрой и просто считывать аргументы из командной строки через argv

2022-11-20 16:52 UTC, SVizor42 commented on ml_project/src/models/predict_pipeline.py
> +                   'data/predicted_target.txt')
Ок. Гидра тоже позволяет передавать параметры через аргументы командной строки :)
https://hydra.cc/docs/tutorials/basic/your_first_app/config_file/

2022-11-20 17:00 UTC, SVizor42 commented on ml_project/src/models/train_pipeline.py
> +    logger.info('Load process data to "data/processed/heart_cleveland_upload.csv"')
Путь можно также передать в строку через f-string

2022-11-20 17:04 UTC, SVizor42 commented on ml_project/src/models/train_pipeline.py
> +from hydra.core.config_store import ConfigStore
Гидру повыше локальных импортов

2022-11-20 17:22 UTC, SVizor42 approved these changes
Теперь уже лучше. Можно ветку сливать.

Рекомендую также почитать про `pytest` и фикстуры: https://docs.pytest.org/en/6.2.x/fixture.html

Я насчитал побольше баллов. **Сумма : 38 баллов**.

2022-11-21 08:19 UTC, merged